import { Inter } from "next/font/google";
import "./globals.css";
import { PersonalStatesContextProvider } from "@/Context/PersonalContext";
import { WorkContextProvider } from "@/Context/WorkContext";
import { SkillsContextProvider } from "@/Context/SkillContext";
import { StrengthContextProvider } from "@/Context/StrengthContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <PersonalStatesContextProvider>
        <WorkContextProvider>
          <SkillsContextProvider>
            <StrengthContextProvider>
              <body className={inter.className}>{children}</body>
            </StrengthContextProvider>
          </SkillsContextProvider>
        </WorkContextProvider>
      </PersonalStatesContextProvider>
    </html>
  );
}
