import { Inter } from "next/font/google";
import "./globals.css";
import { PersonalStatesContextProvider } from "@/Context/PersonalContext";
import { WorkContextProvider } from "@/Context/WorkContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <PersonalStatesContextProvider>
        <WorkContextProvider>
          <body className={inter.className}>{children}</body>
        </WorkContextProvider>
      </PersonalStatesContextProvider>
    </html>
  );
}
